[package]
name = "topology"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0.1"
ordered-float = { version = "5", default-features = false }
serde = { version = "1", features = ["derive"] }
bitflags = { version = "2" }
thiserror = "2"

[features]
dcel = []
graph = []
