[package]
name = "topology"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
ordered-float = { version = "5", default-features = false }
rstar = "0.12.2"
serde = { version = "1", features = ["derive"] }

[features]
dcel = []
graph = []
